### ISSUE TITLE
Node-sass & Sass-loader needs updating

### ISSUE THREAD

**Issue by justanidiot** [SwiftySpartan/Angular-1.5-cli#2]
when bootstrapping the app using:
`gen new {{PROJECT_NAME}}`
errors occur with node-sass postinstall.

the way i resolved this is by uninstalling and reinstalling updated version
of node-sass and sass-loader. If there's a better way of resolving this,
do tell.

ty, gj on the tool.

**Comment by andrewwormald** [comment]
@justanidiot Thanks for your feedback. I can't seem to replicate the issue on my side. Did you have a previous version of node-sass &/or sass-loader prior to installing Angular-1.5-cli?
