### ISSUE TITLE
How to use MaterialJS

### ISSUE THREAD

**Issue by SvenBudak** [SwiftySpartan/Angular-1.5-cli#4]
Hi! I really like the CLI. Thanks for this! But how i can load MaterialJS? I tryed to import ngMaterial in the app.modules.js but the command line didnt find some packages...

```
import angular from 'angular';
import appComponent from './app.component';
import ComponentsModule from './components/components';
import ngMaterial from 'angular-material';

angular.module('app', [
    ComponentsModule.name,
    ngMaterial
]).component('app', appComponent);
```

**Comment by SvenBudak** [comment]
Found the Solution by my self: didnt knowed that i need to load some angular packages to that material works:

```
import angular from 'angular';
import appComponent from './app.component';
import ComponentsModule from './components/components';
import UIRouter from '@uirouter/angularjs';
import ngAnimate from 'angular-animate';
import ngMessages from 'angular-messages';
import ngMaterial from 'angular-material';

angular.module('app', [
    ComponentsModule.name,
    UIRouter,
    ngAnimate,
    ngMessages,
    ngMaterial
]).component('app', appComponent);
```

**Comment by SvenBudak** [comment]
But is there anywhere a guide where i can see how i can use with your CLI the ui-router?

**Comment by andrewwormald** [comment]
@BamiGorengo sorry for late response. I really appreciate your feedback. This is actually something I haven't worked on for a while other than just keeping it going. But I am going to start maintaining this a lot better and will resume working and making it stronger in the next month.

That being said I will need to get back to you on that.

Thanks again for your support
